INSERT INTO recipe (name, servings, category_id, preparation_instruction)
VALUES ('Spaghetti Bolognese', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Boil salted water in a large pot. Add spaghetti and cook according to package instructions until al dente. Drain and set aside. 2. In a skillet, heat olive oil over medium heat. Add finely chopped onions and garlic; sauté until onions are translucent. 3. Add ground beef to the skillet, breaking it up with a wooden spoon. Cook until browned. 4. Stir in chopped tomatoes, tomato paste, and Italian seasoning. Let it simmer for about 20 minutes, stirring occasionally. 5. Serve the Bolognese sauce over the spaghetti, garnishing with grated Parmesan cheese and fresh basil leaves.'),
       ('Vegetable Curry', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Heat coconut oil in a large pot over medium heat. Add chopped onions and sauté until they are golden brown. 2. Stir in minced garlic, ginger, and diced tomatoes. Cook for a few minutes until fragrant. 3. Add diced carrots, bell peppers, and cauliflower florets to the pot. Cook for about 5 minutes, stirring occasionally. 4. Sprinkle curry powder, turmeric, and salt over the vegetables. Mix well to coat. 5. Pour in coconut milk and let the mixture simmer for 20-25 minutes, or until the vegetables are tender. 6. Serve hot with steamed basmati rice or naan bread.'),
       ('Pancakes', 4, (SELECT id FROM category WHERE name = 'Breakfast'),
        '1. In a mixing bowl, combine flour, baking powder, sugar, and salt. In another bowl, whisk together milk, eggs, and melted butter. 2. Pour the wet ingredients into the dry ingredients and mix until just combined; it’s okay if there are lumps. 3. Heat a non-stick skillet over medium heat and lightly grease it with butter. 4. Pour 1/4 cup of batter onto the skillet for each pancake. Cook until bubbles form on the surface, then flip and cook until golden brown. 5. Serve warm with maple syrup, fresh fruit, or whipped cream.'),
       ('Beef Tacos', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a skillet over medium heat, brown the ground beef until fully cooked, draining any excess fat. 2. Stir in taco seasoning and water; bring to a simmer and cook for about 5 minutes until the sauce thickens. 3. While the beef cooks, warm the taco shells in the oven as per package instructions. 4. Assemble the tacos by spooning the beef mixture into each shell. 5. Top with shredded lettuce, diced tomatoes, cheese, sour cream, and salsa as desired. 6. Serve with lime wedges for squeezing on top.'),
       ('Chicken Alfredo', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Cook fettuccine according to package instructions until al dente. Reserve 1 cup of pasta water, then drain. 2. In a large skillet, melt butter over medium heat. Add minced garlic and cook until fragrant, about 1 minute. 3. Pour in heavy cream and bring to a gentle simmer. Stir in grated Parmesan cheese until melted and smooth. 4. Add cooked chicken (sliced or diced) to the sauce and combine. If the sauce is too thick, add reserved pasta water to reach desired consistency. 5. Toss the drained fettuccine in the Alfredo sauce until well coated. 6. Serve immediately, garnished with extra Parmesan and freshly cracked pepper.'),
       ('Greek Salad', 4, (SELECT id FROM category WHERE name = 'Appetizer'),
        '1. In a large bowl, combine chopped cucumbers, diced tomatoes, thinly sliced red onion, and bell pepper. 2. Add pitted Kalamata olives and crumbled feta cheese to the bowl. 3. In a separate small bowl, whisk together olive oil, red wine vinegar, oregano, salt, and pepper to create the dressing. 4. Pour the dressing over the salad and toss gently to combine. 5. Let the salad sit for 10 minutes to allow flavors to meld before serving. 6. Serve chilled or at room temperature, with warm pita bread if desired.'),
       ('Stuffed Shells', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). Cook large pasta shells according to package instructions; drain and set aside. 2. In a bowl, mix ricotta cheese, 1 cup of mozzarella cheese, grated Parmesan, egg, and herbs. 3. Fill each shell with the cheese mixture and place them in a greased baking dish. 4. Pour marinara sauce over the stuffed shells and sprinkle with remaining mozzarella cheese. 5. Cover with foil and bake for 25 minutes. Remove foil and bake for an additional 10 minutes, until cheese is bubbly and golden. 6. Let cool for a few minutes before serving.'),
       ('Chocolate Chip Cookies', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). In a bowl, cream together softened butter, brown sugar, and granulated sugar until light and fluffy. 2. Beat in eggs one at a time, then stir in vanilla extract. 3. In a separate bowl, combine flour, baking soda, and salt; gradually add to the wet mixture, mixing until just combined. 4. Fold in chocolate chips. 5. Drop spoonfuls of dough onto ungreased baking sheets, spacing them apart. 6. Bake for 10-12 minutes or until golden brown. Allow to cool on the sheets for a few minutes before transferring to wire racks.'),
       ('Pumpkin Pie', 8, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 425°F (220°C). Roll out the pie crust and fit it into a pie dish. 2. In a mixing bowl, combine pumpkin puree, sugar, salt, cinnamon, ginger, and nutmeg. 3. Beat in eggs and evaporated milk until smooth. 4. Pour the pumpkin filling into the prepared crust. 5. Bake for 15 minutes, then reduce the oven temperature to 350°F (175°C) and bake for an additional 30-35 minutes or until the filling is set. 6. Allow to cool before serving with whipped cream.'),
       ('Lemon Chicken', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a bowl, mix olive oil, lemon juice, minced garlic, and herbs. 2. Marinate chicken breasts in the mixture for at least 30 minutes or overnight for better flavor. 3. Preheat the grill or oven to 375°F (190°C). 4. Grill or bake the marinated chicken until fully cooked and juices run clear, about 20-25 minutes, turning halfway through. 5. Let the chicken rest for a few minutes, then slice and serve with lemon wedges and a side of steamed vegetables.'),
       ('Fish Tacos', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Season fish fillets with lime juice, chili powder, cumin, salt, and pepper. 2. Heat olive oil in a skillet over medium heat and cook the fish for 3-4 minutes on each side, until flaky. 3. Warm corn tortillas in a separate skillet. 4. Assemble tacos by placing fish in tortillas and topping with cabbage slaw, avocado slices, and a drizzle of lime crema. 5. Serve with extra lime wedges and your favorite hot sauce.'),
       ('Beef Stroganoff', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a large skillet, melt butter over medium heat and add sliced beef. Cook until browned, then remove from the skillet. 2. In the same skillet, add sliced onions and mushrooms; sauté until softened. 3. Return the beef to the skillet and stir in flour, cooking for 1 minute. 4. Gradually add beef broth and Worcestershire sauce, stirring constantly until the sauce thickens. 5. Lower the heat and mix in sour cream; heat through but do not boil. 6. Serve the stroganoff over egg noodles or rice, garnished with fresh parsley.'),
       ('Quinoa Salad', 4, (SELECT id FROM category WHERE name = 'Appetizer'),
        '1. Rinse quinoa under cold water and cook according to package instructions; let it cool. 2. In a large bowl, combine the cooked quinoa with diced cucumber, cherry tomatoes, red onion, and bell pepper. 3. In a small bowl, whisk together olive oil, lemon juice, salt, and pepper for the dressing. 4. Pour the dressing over the salad and toss gently to combine. 5. Add chopped fresh herbs like parsley or cilantro if desired. 6. Serve chilled or at room temperature.'),
       ('Minestrone Soup', 6, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a large pot, heat olive oil and sauté chopped onions, carrots, and celery until softened. 2. Add minced garlic and cook for another minute. 3. Stir in diced tomatoes, vegetable broth, and seasonings. 4. Bring to a boil, then reduce heat and simmer for 20 minutes. 5. Add green beans, zucchini, and cooked pasta; simmer until vegetables are tender. 6. Stir in kidney beans and spinach; heat through. Serve hot, garnished with grated Parmesan cheese if desired.'),
       ('Caprese Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. Slice fresh mozzarella and tomatoes into thick slices. 2. Alternate the mozzarella and tomato slices on a serving platter. 3. Drizzle with olive oil and balsamic vinegar, then sprinkle with salt and pepper. 4. Top with fresh basil leaves. 5. Serve immediately as a refreshing side dish or appetizer.'),
       ('Creamy Mushroom Risotto', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Heat broth in a saucepan and keep warm. In a separate pot, melt butter and sauté onions until translucent. 2. Add arborio rice and cook, stirring for 1-2 minutes until lightly toasted. 3. Gradually add warm broth, one ladle at a time, stirring constantly until absorbed. 4. After about 15 minutes, add sautéed mushrooms. 5. Continue adding broth and stirring until the rice is creamy and al dente, about 20 minutes total. 6. Stir in grated Parmesan cheese and serve immediately, garnished with parsley.'),
       ('Shrimp Fried Rice', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Heat a large skillet or wok over medium-high heat. Add vegetable oil and sauté shrimp until pink and cooked through. Remove and set aside. 2. In the same skillet, add more oil and stir-fry garlic, onions, and mixed vegetables until tender. 3. Push the vegetables to the side and scramble the eggs in the center. 4. Add cooked rice, soy sauce, and shrimp back to the skillet; mix everything together until heated through. 5. Garnish with green onions and serve hot.'),
       ('Spinach and Feta Stuffed Chicken', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). In a bowl, combine chopped spinach, crumbled feta, and minced garlic. 2. Slice a pocket into each chicken breast and stuff with the spinach mixture. 3. Season the outside of the chicken with salt, pepper, and olive oil. 4. Place the chicken in a greased baking dish and bake for 25-30 minutes until cooked through. 5. Serve with roasted vegetables or a fresh salad.'),
       ('Tomato Basil Bruschetta', 4, (SELECT id FROM category WHERE name = 'Appetizer'),
        '1. Preheat the oven to 400°F (200°C). Slice a baguette into thin rounds and arrange on a baking sheet. 2. Brush the bread slices with olive oil and bake for 5-7 minutes until lightly toasted. 3. In a bowl, combine diced tomatoes, minced garlic, chopped basil, olive oil, and balsamic vinegar; season with salt and pepper. 4. Spoon the tomato mixture onto the toasted bread just before serving.'),
       ('Apple Crisp', 8, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). In a mixing bowl, combine sliced apples, sugar, cinnamon, and lemon juice; toss to coat. 2. Spread the apple mixture in a greased baking dish. 3. In another bowl, mix oats, flour, brown sugar, and melted butter until crumbly. 4. Sprinkle the crumb mixture over the apples. 5. Bake for 30-35 minutes until the apples are tender and the topping is golden brown. Serve warm with ice cream.'),
       ('Chili Con Carne', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a large pot, brown ground beef over medium heat; drain excess fat. 2. Add chopped onions and garlic, cooking until softened. 3. Stir in diced tomatoes, kidney beans, chili powder, cumin, and salt. 4. Bring to a boil, then reduce heat and simmer for 30 minutes, stirring occasionally. 5. Serve hot, garnished with shredded cheese and sour cream.'),
       ('Eggplant Parmesan', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). Slice eggplant into rounds and sprinkle with salt; let sit for 30 minutes to draw out moisture. 2. Rinse and pat dry, then coat eggplant slices in flour, beaten egg, and breadcrumbs. 3. Fry in olive oil until golden brown on both sides, then drain on paper towels. 4. In a baking dish, layer marinara sauce, eggplant, mozzarella, and Parmesan. Repeat layers until all ingredients are used. 5. Bake for 30-35 minutes until bubbly and golden. Let rest before serving.'),
       ('Banana Bread', 1, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). In a mixing bowl, mash ripe bananas with a fork. 2. Mix in melted butter, sugar, egg, and vanilla extract until smooth. 3. In another bowl, combine flour, baking soda, and salt; gradually add to the banana mixture. 4. Pour the batter into a greased loaf pan and bake for 60-65 minutes or until a toothpick comes out clean. 5. Let cool before slicing.'),
       ('Garlic Butter Shrimp', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a skillet, melt butter over medium heat. Add minced garlic and sauté until fragrant. 2. Add peeled shrimp and cook until they turn pink and opaque, about 2-3 minutes per side. 3. Squeeze fresh lemon juice over the shrimp and sprinkle with parsley. 4. Serve over rice or pasta.'),
       ('Caesar Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. Tear romaine lettuce into bite-sized pieces and place in a large bowl. 2. In a small bowl, whisk together olive oil, lemon juice, Worcestershire sauce, minced garlic, and Dijon mustard. 3. Pour the dressing over the lettuce and toss to coat. 4. Add croutons and grated Parmesan cheese; toss again. 5. Serve immediately.'),
       ('Beef and Broccoli Stir-Fry', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Marinate sliced beef in soy sauce, cornstarch, and sesame oil for 15 minutes. 2. Heat vegetable oil in a wok and stir-fry the beef until browned; remove and set aside. 3. In the same wok, stir-fry broccoli florets and sliced bell peppers until tender-crisp. 4. Return the beef to the wok, add oyster sauce, and toss to combine. 5. Serve over cooked rice or noodles.'),
       ('Peach Cobbler', 8, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). In a bowl, mix sliced peaches, sugar, and lemon juice; set aside. 2. In another bowl, combine flour, sugar, baking powder, and milk to create a batter. 3. Pour melted butter into a greased baking dish and pour the batter over it without stirring. 4. Spoon the peach mixture on top of the batter. 5. Bake for 30-35 minutes until golden brown. Serve warm with ice cream.'),
       ('Baked Ziti', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). Cook ziti pasta according to package instructions; drain. 2. In a mixing bowl, combine cooked pasta with marinara sauce, ricotta cheese, and half of the mozzarella cheese. 3. Transfer the mixture to a greased baking dish and top with remaining mozzarella cheese. 4. Bake for 20-25 minutes until bubbly and golden brown. Serve hot.'),
       ('Teriyaki Chicken', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a bowl, mix soy sauce, brown sugar, rice vinegar, garlic, and ginger to create the teriyaki sauce. 2. Marinate chicken breasts in the sauce for at least 30 minutes. 3. Preheat the grill to medium-high heat. 4. Grill chicken for 6-8 minutes on each side until cooked through, brushing with remaining sauce during grilling. 5. Slice and serve with steamed rice and vegetables.'),
       ('Chocolate Mousse', 6, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Melt dark chocolate in a double boiler or microwave; let cool slightly. 2. In a bowl, whisk egg yolks and sugar until pale and creamy. 3. Stir the melted chocolate into the egg mixture. 4. In a separate bowl, whip heavy cream until soft peaks form, then fold into the chocolate mixture. 5. Spoon into individual cups and refrigerate for at least 2 hours before serving.'),
       ('Butternut Squash Soup', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. Preheat the oven to 400°F (200°C). Cut butternut squash in half lengthwise, scoop out seeds, and place cut side down on a baking sheet. 2. Roast for 30-40 minutes until tender. 3. In a pot, heat olive oil over medium heat and sauté onions and garlic until translucent. 4. Scoop out the roasted squash and add to the pot with vegetable broth and seasonings. 5. Blend until smooth; return to heat to warm through. Serve hot with a drizzle of olive oil.'),
       ('Beef Tacos', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a skillet, brown ground beef with diced onions and season with taco seasoning. 2. Warm taco shells in the oven. 3. Fill each shell with the beef mixture and top with shredded lettuce, diced tomatoes, cheese, and sour cream. 4. Serve with salsa on the side.'),
       ('Vegetable Stir-Fry', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Heat vegetable oil in a wok over high heat. 2. Add sliced bell peppers, broccoli, and carrots; stir-fry for 3-4 minutes until tender-crisp. 3. Add minced garlic and ginger; stir-fry for another minute. 4. Pour in soy sauce and toss everything to coat. 5. Serve over cooked rice or noodles.'),
       ('French Onion Soup', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a large pot, melt butter over medium heat. Add sliced onions and cook until caramelized, about 30 minutes. 2. Stir in flour and cook for 1-2 minutes. 3. Add beef broth, thyme, and bay leaf; simmer for 30 minutes. 4. Remove bay leaf and ladle soup into bowls; top with toasted bread and melted cheese. Serve hot.'),
       ('Chocolate Chip Cookies', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 375°F (190°C). In a bowl, cream together butter and sugar until light and fluffy. 2. Beat in eggs and vanilla extract. 3. Gradually mix in flour, baking soda, and salt; fold in chocolate chips. 4. Drop spoonfuls of dough onto baking sheets. 5. Bake for 9-11 minutes until edges are golden. Let cool on wire racks.'),
       ('Lentil Soup', 6, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a pot, heat olive oil and sauté onions, carrots, and celery until softened. 2. Add garlic, diced tomatoes, lentils, and vegetable broth. 3. Season with thyme, bay leaf, salt, and pepper. 4. Bring to a boil, then reduce heat and simmer for 30-40 minutes until lentils are tender. 5. Remove bay leaf before serving. Serve hot, garnished with fresh herbs.'),
       ('Chicken Parmesan', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). 2. Season chicken breasts with salt and pepper, then coat in flour, dip in beaten egg, and coat in breadcrumbs. 3. Heat olive oil in a skillet and fry chicken until golden on both sides. 4. Place chicken in a baking dish, top with marinara sauce and mozzarella cheese. 5. Bake for 25-30 minutes until chicken is cooked through and cheese is bubbly. Serve hot.'),
       ('Pasta Primavera', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Cook pasta according to package instructions; drain. 2. In a large skillet, heat olive oil and sauté garlic until fragrant. 3. Add seasonal vegetables and cook until tender. 4. Toss cooked pasta with the sautéed vegetables and add salt, pepper, and grated Parmesan cheese to taste. 5. Serve warm with additional cheese if desired.'),
       ('Vegetable Curry', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a large pot, heat vegetable oil over medium heat. Add chopped onions, ginger, and garlic, sauté until softened. 2. Stir in curry powder and cook for 1-2 minutes. 3. Add diced vegetables and cook for 5-7 minutes until slightly tender. 4. Pour in coconut milk and vegetable broth; bring to a simmer. 5. Cook for 15-20 minutes until vegetables are fully tender. Serve with rice or naan bread.'),
       ('Stuffed Bell Peppers', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). Slice the tops off bell peppers and remove seeds. 2. In a skillet, brown ground beef or turkey with onions and garlic. 3. Add cooked rice, diced tomatoes, and seasonings to the meat mixture; stir to combine. 4. Stuff each pepper with the mixture and place in a baking dish. 5. Bake for 30-35 minutes until peppers are tender. Serve hot.'),
       ('Pineapple Fried Rice', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Heat vegetable oil in a large skillet or wok over medium heat. 2. Add diced onion, carrots, and peas; sauté until tender. 3. Push the vegetables to the side and scramble the eggs in the center. 4. Add cooked rice, soy sauce, and pineapple; mix everything together until heated through. 5. Garnish with green onions and serve hot.'),
       ('Pumpkin Spice Muffins', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). In a bowl, combine flour, sugar, baking powder, cinnamon, nutmeg, and salt. 2. In another bowl, whisk together pumpkin puree, eggs, and oil until smooth. 3. Gradually add the wet ingredients to the dry ingredients, mixing until just combined. 4. Pour the batter into a greased muffin tin, filling each cup about 2/3 full. 5. Bake for 18-20 minutes or until a toothpick inserted comes out clean. Let cool before serving.'),
       ('Shrimp Tacos', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a bowl, toss shrimp with lime juice, garlic, cumin, and salt; let marinate for 15 minutes. 2. Heat a skillet over medium-high heat and cook shrimp for 2-3 minutes per side until pink and cooked through. 3. Warm corn tortillas and fill each with shrimp, avocado slices, and a drizzle of lime crema. 4. Serve with salsa and lime wedges.'),
       ('Quinoa Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. Rinse quinoa under cold water and cook according to package instructions; let cool. 2. In a large bowl, combine cooked quinoa, diced cucumbers, tomatoes, red onion, and parsley. 3. In a small bowl, whisk together olive oil, lemon juice, salt, and pepper. 4. Pour the dressing over the salad and toss to combine. 5. Serve chilled or at room temperature.'),
       ('Mango Sticky Rice', 8, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Rinse sticky rice under cold water and soak for at least 1 hour. 2. Steam the soaked rice for 30-40 minutes until tender. 3. In a saucepan, combine coconut milk, sugar, and salt; heat until the sugar dissolves. 4. Pour half of the coconut milk mixture over the cooked rice, stirring gently. 5. Serve the sticky rice with sliced mango and drizzle with the remaining coconut milk.'),
       ('Potato Leek Soup', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a large pot, melt butter and sauté sliced leeks until softened. 2. Add diced potatoes and broth; bring to a boil. 3. Reduce heat and simmer until potatoes are tender. 4. Blend the soup until smooth; season with salt and pepper. 5. Serve hot, garnished with chopped chives.'),
       ('Baked Salmon', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 400°F (200°C). Line a baking sheet with parchment paper. 2. Place salmon fillets on the prepared baking sheet; season with salt, pepper, and lemon slices. 3. Bake for 12-15 minutes until the salmon is flaky. 4. Serve with steamed vegetables or a salad.'),
       ('Chocolate Cake', 8, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). Grease and flour two 9-inch round cake pans. 2. In a large bowl, combine flour, cocoa powder, sugar, baking powder, and salt. 3. Add eggs, milk, oil, and vanilla; mix until smooth. 4. Divide the batter evenly between the prepared pans. 5. Bake for 30-35 minutes; let cool before frosting.'),
       ('Grilled Vegetable Skewers', 4, (SELECT id FROM category WHERE name = 'Appetizer'),
        '1. Preheat the grill to medium heat. 2. Thread bell peppers, zucchini, and mushrooms onto skewers. 3. Brush with olive oil and season with salt and pepper. 4. Grill for 10-15 minutes, turning occasionally, until tender. 5. Serve warm with dipping sauce.'),
       ('Caesar Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. In a large bowl, combine romaine lettuce, croutons, and Parmesan cheese. 2. In a small bowl, whisk together olive oil, lemon juice, Worcestershire sauce, garlic, and anchovies. 3. Pour the dressing over the salad and toss to coat. 4. Serve immediately, garnished with additional cheese.'),
       ('Sushi Rolls', 6, (SELECT id FROM category WHERE name = 'Appetizer'),
        '1. Cook sushi rice according to package instructions and let cool. 2. Place a sheet of nori on a bamboo mat; spread a thin layer of rice on top. 3. Add fillings such as cucumber, avocado, and fish. 4. Roll tightly and slice into pieces. 5. Serve with soy sauce and wasabi.'),
       ('Eggplant Parmesan', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). Slice eggplant and sprinkle with salt; let sit for 30 minutes to remove moisture. 2. Rinse and pat dry, then dip in flour, egg, and breadcrumbs. 3. Fry until golden, then layer in a baking dish with marinara sauce and mozzarella cheese. 4. Bake for 25-30 minutes until bubbly. Serve hot.'),
       ('Spinach Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. In a large bowl, combine fresh spinach, sliced strawberries, almonds, and feta cheese. 2. In a small bowl, whisk together olive oil, balsamic vinegar, and honey. 3. Pour the dressing over the salad and toss to combine. 4. Serve immediately.'),
       ('Roasted Vegetable Medley', 4, (SELECT id FROM category WHERE name = 'Side Dish'),
        '1. Preheat the oven to 425°F (220°C). 2. Chop seasonal vegetables like zucchini, bell peppers, and carrots; toss with olive oil, salt, and pepper. 3. Spread on a baking sheet in a single layer. 4. Roast for 20-25 minutes until tender. Serve warm.'),
       ('Chili', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a large pot, sauté diced onions and garlic until softened. 2. Add ground beef, cook until browned. 3. Stir in diced tomatoes, kidney beans, and chili powder; simmer for 30 minutes. 4. Season with salt and pepper. Serve hot, topped with cheese.'),
       ('Fruit Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. Chop assorted fresh fruits like apples, bananas, and berries. 2. In a bowl, combine the fruit and squeeze lime juice over it. 3. Toss gently to combine. 4. Serve chilled or at room temperature.'),
       ('Teriyaki Chicken', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Marinate chicken breasts in teriyaki sauce for at least 30 minutes. 2. Heat a skillet over medium heat and cook chicken for 6-7 minutes per side until cooked through. 3. Slice and serve over rice, drizzling with extra teriyaki sauce. 4. Garnish with green onions.'),
       ('Apple Pie', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 425°F (220°C). Roll out pie crust and place in a pie dish. 2. In a bowl, toss sliced apples with sugar, cinnamon, and lemon juice. 3. Pour the apple mixture into the crust and cover with a top crust. 4. Bake for 45-50 minutes until apples are soft and crust is golden. Serve warm.'),
       ('Caprese Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. Slice fresh mozzarella and tomatoes; layer with basil leaves. 2. Drizzle with olive oil and balsamic vinegar. 3. Season with salt and pepper. 4. Serve immediately as an appetizer.'),
       ('Baked Ziti', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). 2. Cook ziti pasta according to package instructions; drain. 3. In a large bowl, combine cooked pasta, marinara sauce, ricotta cheese, and mozzarella cheese. 4. Pour into a baking dish and top with additional mozzarella. 5. Bake for 25-30 minutes until cheese is melted and bubbly. Serve hot.'),
       ('Cobb Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. In a large bowl, layer chopped romaine lettuce, diced tomatoes, cooked chicken, bacon, avocado, and blue cheese. 2. Drizzle with ranch dressing. 3. Toss gently before serving.'),
       ('Banana Bread', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). In a bowl, mash ripe bananas. 2. Mix in sugar, eggs, and melted butter. 3. Stir in flour, baking soda, and salt until just combined. 4. Pour batter into a greased loaf pan. 5. Bake for 60-65 minutes until a toothpick comes out clean. Let cool before slicing.'),
       ('Chicken Fajitas', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a skillet, sauté sliced bell peppers and onions until softened. 2. Add sliced chicken breast and cook until no longer pink. 3. Season with fajita seasoning. 4. Serve with warm tortillas, guacamole, and salsa.'),
       ('Roasted Brussels Sprouts', 4, (SELECT id FROM category WHERE name = 'Side Dish'),
        '1. Preheat the oven to 400°F (200°C). Trim and halve Brussels sprouts. 2. Toss with olive oil, salt, and pepper; spread on a baking sheet. 3. Roast for 20-25 minutes until crispy and golden. Serve warm.'),
       ('Clam Chowder', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a pot, cook bacon until crispy; remove and set aside. 2. In the same pot, sauté onions and celery until softened. 3. Stir in potatoes and broth; simmer until potatoes are tender. 4. Add clams and cream; cook until heated through. Serve hot, garnished with bacon.'),
       ('Lasagna', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). 2. In a skillet, brown ground beef and onions; drain excess fat. 3. Layer cooked lasagna noodles, meat sauce, ricotta cheese, and mozzarella in a baking dish. 4. Repeat layers and top with mozzarella. 5. Bake for 45-50 minutes until cheese is bubbly. Serve hot.'),
       ('Cheese Quesadilla', 4, (SELECT id FROM category WHERE name = 'Appetizer'),
        '1. Heat a skillet over medium heat; place a tortilla in the skillet. 2. Sprinkle cheese on one half and fold the tortilla over. 3. Cook until golden brown on both sides; remove and cut into wedges. 4. Serve with salsa or guacamole.'),
       ('Curry Lentils', 4, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a pot, sauté onions and garlic until fragrant. 2. Add curry powder and lentils; stir to coat. 3. Pour in vegetable broth and simmer until lentils are tender. 4. Season with salt and pepper. Serve hot with rice or bread.'),
       ('Blueberry Muffins', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 375°F (190°C). In a bowl, combine flour, sugar, baking powder, and salt. 2. In another bowl, whisk together milk, eggs, and melted butter. 3. Gradually add the wet ingredients to the dry ingredients, folding in blueberries. 4. Pour into a greased muffin tin and bake for 18-20 minutes until golden. Let cool before serving.'),
       ('Thai Green Curry', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a pot, heat coconut oil and sauté green curry paste until fragrant. 2. Add sliced vegetables and cook until tender. 3. Pour in coconut milk and simmer for 10 minutes. 4. Add protein of choice (tofu, chicken, shrimp) and cook until done. Serve with rice.'),
       ('Potato Salad', 4, (SELECT id FROM category WHERE name = 'Side Dish'),
        '1. Boil potatoes until tender; drain and let cool. 2. In a bowl, combine diced potatoes, mayonnaise, mustard, chopped celery, and green onions. 3. Season with salt and pepper. 4. Chill before serving.'),
       ('Chocolate Chip Cookies', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 375°F (190°C). In a bowl, cream together butter and sugar. 2. Add eggs and vanilla; mix well. 3. Stir in flour, baking soda, and chocolate chips. 4. Drop spoonfuls onto a baking sheet and bake for 10-12 minutes until golden. Let cool before serving.'),
       ('Vegetable Stir-Fry', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a wok, heat oil over high heat. 2. Add chopped vegetables (broccoli, bell peppers, carrots) and stir-fry for 5-7 minutes. 3. Add soy sauce and stir to coat. 4. Serve over rice or noodles.'),
       ('Minestrone Soup', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a pot, sauté onions, carrots, and celery until softened. 2. Add diced tomatoes, vegetable broth, and beans. 3. Stir in pasta and cook until tender. 4. Season with herbs and serve hot.'),
       ('Tiramisu', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. In a bowl, mix coffee and rum. 2. Dip ladyfinger cookies into the coffee mixture and layer in a dish. 3. In another bowl, whisk mascarpone cheese with sugar and cocoa powder. 4. Spread over the ladyfingers and repeat layers. 5. Chill for at least 4 hours before serving.'),
       ('Stuffed Bell Peppers', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). 2. Cut tops off bell peppers and remove seeds. 3. In a bowl, mix cooked rice, ground beef, diced tomatoes, and spices. 4. Stuff mixture into peppers and place in a baking dish. 5. Bake for 30-35 minutes until peppers are tender.'),
       ('Fruit Tart', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 375°F (190°C). Roll out tart crust and place in a tart pan. 2. Blind bake for 15 minutes until golden. 3. Fill with pastry cream and top with assorted fruits. 4. Glaze with apricot jam. Chill before serving.'),
       ('Garlic Bread', 4, (SELECT id FROM category WHERE name = 'Side Dish'),
        '1. Preheat the oven to 375°F (190°C). Slice a baguette in half and spread butter and minced garlic on top. 2. Sprinkle with parsley and mozzarella cheese. 3. Bake for 10-12 minutes until golden and toasted. Serve warm.'),
       ('Pumpkin Soup', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a pot, sauté onions and garlic until softened. 2. Add canned pumpkin, vegetable broth, and spices; bring to a simmer. 3. Blend until smooth. 4. Serve hot with cream and pumpkin seeds.'),
       ('Honey Glazed Carrots', 4, (SELECT id FROM category WHERE name = 'Side Dish'),
        '1. In a pan, melt butter over medium heat. 2. Add sliced carrots and sauté for 5 minutes. 3. Drizzle with honey and season with salt; cook until tender. Serve warm.'),
       ('Chicken Noodle Soup', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a pot, cook chicken until done; remove and shred. 2. In the same pot, sauté onions, carrots, and celery. 3. Add chicken broth, noodles, and shredded chicken; simmer until noodles are tender. 4. Season with salt and pepper. Serve hot.'),
       ('Peach Cobbler', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). In a baking dish, combine sliced peaches, sugar, and lemon juice. 2. In a bowl, mix flour, sugar, baking powder, and milk to make batter. 3. Pour batter over peaches and bake for 30-35 minutes until golden. Serve warm.'),
       ('Chicken Stir-Fry', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a wok, heat oil over high heat. 2. Add sliced chicken and cook until browned. 3. Add vegetables and stir-fry for 5-7 minutes. 4. Pour in soy sauce and serve over rice.'),
       ('Baked Apples', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). Core apples and place in a baking dish. 2. Fill centers with brown sugar, cinnamon, and walnuts. 3. Bake for 20-25 minutes until tender. Serve warm with ice cream.'),
       ('Chicken Parmesan', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). 2. Bread and fry chicken cutlets until golden. 3. Layer chicken with marinara sauce and mozzarella cheese in a baking dish. 4. Bake for 25-30 minutes until cheese is bubbly. Serve hot with pasta.'),
       ('Baked Sweet Potatoes', 4, (SELECT id FROM category WHERE name = 'Side Dish'),
        '1. Preheat the oven to 400°F (200°C). 2. Pierce sweet potatoes with a fork and bake for 45-60 minutes until soft. 3. Cut open and top with butter, brown sugar, and cinnamon. Serve warm.'),
       ('Raspberry Sorbet', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. In a blender, puree raspberries and sugar until smooth. 2. Freeze in an airtight container for at least 4 hours. 3. Serve scoops in bowls or cones.'),
       ('Pasta Primavera', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Cook pasta according to package instructions; drain. 2. In a skillet, sauté mixed vegetables in olive oil until tender. 3. Toss with pasta, garlic, and Parmesan cheese. 4. Serve warm.'),
       ('Stuffed Mushrooms', 6, (SELECT id FROM category WHERE name = 'Appetizer'),
        '1. Preheat the oven to 375°F (190°C). 2. Remove stems from mushrooms and chop finely. 3. In a bowl, mix chopped stems, cream cheese, garlic, and herbs. 4. Stuff the mixture into mushroom caps and bake for 20 minutes until golden. Serve warm.'),
       ('Key Lime Pie', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). 2. In a bowl, combine graham cracker crumbs, sugar, and melted butter; press into a pie pan. 3. In another bowl, whisk together lime juice, egg yolks, and sweetened condensed milk. 4. Pour into the crust and bake for 10-15 minutes. Chill before serving.'),
       ('Pesto Pasta', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Cook pasta according to package instructions; drain. 2. In a bowl, mix cooked pasta with pesto sauce until well coated. 3. Serve warm, garnished with Parmesan cheese.'),
       ('Carrot Cake', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). In a bowl, mix flour, sugar, baking powder, baking soda, and spices. 2. In another bowl, beat eggs and mix with oil and grated carrots. 3. Combine wet and dry ingredients and pour into a cake pan. 4. Bake for 30-35 minutes until a toothpick comes out clean. Cool before frosting.'),
       ('Falafel', 6, (SELECT id FROM category WHERE name = 'Appetizer'),
        '1. Soak chickpeas overnight, then drain and blend with garlic, onion, parsley, and spices. 2. Form into balls and fry until golden. 3. Serve with tahini sauce and pita bread.'),
       ('Zucchini Noodles', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Spiralize zucchini into noodles. 2. In a skillet, sauté garlic and cherry tomatoes in olive oil. 3. Add zucchini noodles and cook for 3-5 minutes. 4. Serve with grated cheese.'),
       ('Peanut Butter Cookies', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). In a bowl, mix peanut butter, sugar, and egg until smooth. 2. Roll into balls and place on a baking sheet. 3. Press with a fork and bake for 10-12 minutes. Let cool before serving.'),
       ('Tom Yum Soup', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a pot, bring chicken broth to a boil. 2. Add lemongrass, kaffir lime leaves, and galangal. 3. Stir in shrimp and mushrooms; cook until shrimp is done. 4. Season with fish sauce and lime juice before serving.'),
       ('Cucumber Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. Slice cucumbers and red onion thinly. 2. In a bowl, mix vinegar, sugar, and salt to make dressing. 3. Pour over cucumbers and toss to coat. 4. Chill before serving.'),
       ('Chili', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a pot, brown ground beef with onions. 2. Add beans, tomatoes, chili powder, and simmer for 30 minutes. 3. Serve hot with toppings like cheese and sour cream.'),
       ('Caprese Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. Slice fresh mozzarella and tomatoes. 2. Layer slices with basil leaves. 3. Drizzle with balsamic glaze and olive oil. 4. Season with salt and pepper before serving.'),
       ('Vegetable Soup', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a pot, sauté onions and garlic. 2. Add chopped vegetables (carrots, potatoes, peas) and vegetable broth. 3. Season with herbs and simmer until veggies are tender. Serve hot.'),
       ('Greek Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. Chop cucumbers, tomatoes, and bell peppers. 2. Mix with olives, feta cheese, and red onion. 3. Drizzle with olive oil and lemon juice. 4. Season with oregano before serving.'),
       ('Butternut Squash Risotto', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a pot, sauté onions and garlic in butter. 2. Add arborio rice and stir until coated. 3. Gradually add vegetable broth, stirring until absorbed. 4. Stir in roasted butternut squash and Parmesan cheese before serving.'),
       ('Eggplant Parmesan', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). 2. Slice eggplant, salt, and let sit to draw out moisture. 3. Bread and fry slices until golden. 4. Layer with marinara sauce and mozzarella in a baking dish and bake for 25-30 minutes. Serve hot.'),
       ('Avocado Toast', 6, (SELECT id FROM category WHERE name = 'Snack'),
        '1. Toast slices of bread. 2. Mash avocado and mix with lemon juice and salt. 3. Spread avocado on toast and top with radishes or poached eggs. Serve immediately.'),
       ('Rice Pudding', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. In a pot, combine rice, milk, sugar, and vanilla. 2. Cook over low heat, stirring until thickened. 3. Serve warm or chilled, topped with cinnamon.'),
       ('Spaghetti Aglio e Olio', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Cook spaghetti according to package instructions. 2. In a pan, sauté minced garlic in olive oil. 3. Toss cooked spaghetti in garlic oil and add parsley. 4. Serve warm with grated Parmesan.'),
       ('Lentil Soup', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a pot, sauté onions and carrots. 2. Add lentils, diced tomatoes, vegetable broth, and spices. 3. Simmer until lentils are tender. Serve hot.'),
       ('Mango Mousse', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. In a blender, puree ripe mangoes until smooth. 2. In a bowl, whip cream until soft peaks form. 3. Gently fold mango puree into whipped cream. 4. Chill before serving.'),
       ('Grilled Cheese Sandwich', 6, (SELECT id FROM category WHERE name = 'Snack'),
        '1. Heat a skillet over medium heat. 2. Butter bread slices and place cheese in between. 3. Grill until golden brown on both sides. Serve warm.'),
       ('Pineapple Fried Rice', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a wok, heat oil and add cooked rice. 2. Stir in diced pineapple, soy sauce, and vegetables. 3. Fry until heated through. 4. Serve warm, garnished with green onions.'),
       ('Coconut Macaroons', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 325°F (165°C). 2. In a bowl, mix shredded coconut, condensed milk, and vanilla. 3. Form into small balls and place on a baking sheet. 4. Bake for 15-20 minutes until golden. Let cool before serving.'),
       ('Sweet Potato Fries', 6, (SELECT id FROM category WHERE name = 'Snack'),
        '1. Preheat the oven to 425°F (220°C). 2. Cut sweet potatoes into fries and toss with olive oil and salt. 3. Bake for 20-25 minutes until crispy. Serve warm.'),
       ('Crispy Tofu Stir-Fry', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Press and cube tofu, then pan-fry until crispy. 2. In a wok, heat oil and add mixed vegetables. 3. Stir in soy sauce and toss in crispy tofu. 4. Serve over rice.'),
       ('Chocolate Mousse', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Melt dark chocolate and let cool. 2. In a bowl, whip cream until soft peaks form. 3. Fold melted chocolate into whipped cream. 4. Chill before serving.'),
       ('Fried Rice', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a wok, heat oil and add cooked rice. 2. Stir in diced vegetables and soy sauce. 3. Fry until heated through. 4. Serve warm.'),
       ('Potato Salad', 4, (SELECT id FROM category WHERE name = 'Side Dish'),
        '1. Boil potatoes until tender; cool and chop. 2. In a bowl, mix mayonnaise, mustard, celery, and onions. 3. Stir in potatoes and season with salt and pepper. Chill before serving.'),
       ('Chocolate Cake', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). In a bowl, mix flour, cocoa powder, sugar, and baking soda. 2. Add eggs, milk, and oil; mix until smooth. 3. Pour into a cake pan and bake for 30-35 minutes. Cool before frosting.'),
       ('Shrimp Tacos', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a bowl, toss shrimp with lime juice and spices. 2. Grill shrimp until cooked through. 3. Serve in tortillas with cabbage slaw and avocado.'),
       ('Corn on the Cob', 4, (SELECT id FROM category WHERE name = 'Side Dish'),
        '1. Bring a pot of salted water to a boil. 2. Add corn and cook for 8-10 minutes. 3. Serve hot with butter and salt.'),
       ('Vegetable Quesadilla', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Heat a skillet and place a tortilla. 2. Layer with cheese and mixed vegetables. 3. Top with another tortilla and cook until golden, flipping once. Serve with salsa.'),
       ('Chocolava Cake', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 375°F (190°C). 2. In a bowl, mix melted chocolate and butter. 3. Stir in sugar, eggs, and flour. 4. Pour into ramekins and bake for 12-15 minutes until edges are firm. Serve warm with ice cream.'),
       ('Mediterranean Chickpea Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. In a bowl, combine chickpeas, cucumber, tomatoes, red onion, and parsley. 2. Drizzle with olive oil and lemon juice. 3. Season with salt and pepper before serving.'),
       ('Stuffed Zucchini', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). 2. Cut zucchini in half and scoop out the centers. 3. Mix the scooped zucchini with ground meat, spices, and cook. 4. Stuff the mixture back into the zucchini halves and bake for 20-25 minutes. Serve hot.'),
       ('Apple Pie', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 425°F (220°C). 2. Roll out dough and fit into pie pan. 3. Mix sliced apples with sugar, cinnamon, and nutmeg. 4. Fill crust with apple mixture, top with crust, and bake for 40-45 minutes. Serve warm.'),
       ('Fattoush Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. Chop romaine lettuce, tomatoes, and cucumbers. 2. Add toasted pita, radishes, and parsley. 3. Dress with olive oil, lemon juice, and sumac. 4. Toss and serve immediately.'),
       ('Baked Salmon', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 400°F (200°C). 2. Place salmon fillets on a baking sheet and season with salt and pepper. 3. Bake for 12-15 minutes until cooked through. Serve with lemon wedges.'),
       ('Pasta Primavera', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Cook pasta according to package instructions. 2. In a skillet, sauté garlic and seasonal vegetables. 3. Toss with cooked pasta and olive oil. 4. Serve warm with Parmesan cheese.'),
       ('Raspberry Sorbet', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Blend raspberries with sugar and lemon juice until smooth. 2. Freeze the mixture until firm, stirring occasionally. 3. Serve chilled.'),
       ('Chocolate Chip Cookies', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 350°F (175°C). 2. Cream together butter and sugar. 3. Beat in eggs and vanilla. 4. Gradually mix in flour and chocolate chips; drop spoonfuls onto baking sheet. 5. Bake for 10-12 minutes. Let cool before serving.'),
       ('Cabbage Rolls', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Cook cabbage leaves until soft. 2. In a bowl, mix ground meat, rice, and spices. 3. Roll the mixture in cabbage leaves and place in a pot. 4. Cover with tomato sauce and simmer until cooked through.'),
       ('Tiramisu', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Brew espresso and let cool. 2. In a bowl, mix mascarpone cheese, sugar, and whipped cream. 3. Dip ladyfingers in espresso and layer with mascarpone mixture. 4. Refrigerate for at least 4 hours before serving.'),
       ('Grilled Vegetable Skewers', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat grill to medium heat. 2. Skewer seasonal vegetables and brush with olive oil. 3. Grill until charred, turning occasionally. Serve warm.'),
       ('Pumpkin Pie', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 425°F (220°C). 2. Mix pumpkin puree with sugar, cinnamon, and nutmeg. 3. Pour into pie crust and bake for 40-45 minutes. Serve warm.'),
       ('Fried Chicken', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Marinate chicken pieces in buttermilk. 2. Dredge in flour and seasonings. 3. Fry in hot oil until golden brown. Serve hot.'),
       ('Zucchini Noodles', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Spiralize zucchini into noodles. 2. In a skillet, sauté garlic and zucchini noodles. 3. Season with salt, pepper, and toss with marinara sauce. Serve warm.'),
       ('Blueberry Muffins', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. Preheat the oven to 375°F (190°C). 2. In a bowl, mix flour, sugar, baking powder, and salt. 3. In another bowl, whisk eggs, milk, and melted butter. 4. Combine the wet and dry ingredients and fold in blueberries. Pour into muffin tins and bake for 20-25 minutes.'),
       ('Tom Yum Soup', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. Bring chicken broth to a boil. 2. Add lemongrass, kaffir lime leaves, and galangal. 3. Stir in shrimp and mushrooms; cook until shrimp is done. 4. Season with fish sauce and lime juice before serving.'),
       ('Cucumber Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. Slice cucumbers and red onion thinly. 2. In a bowl, mix vinegar, sugar, and salt to make dressing. 3. Pour over cucumbers and toss to coat. 4. Chill before serving.'),
       ('Chili', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a pot, brown ground beef with onions. 2. Add beans, tomatoes, chili powder, and simmer for 30 minutes. 3. Serve hot with toppings like cheese and sour cream.'),
       ('Caprese Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. Slice fresh mozzarella and tomatoes. 2. Layer slices with basil leaves. 3. Drizzle with balsamic glaze and olive oil. 4. Season with salt and pepper before serving.'),
       ('Vegetable Soup', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a pot, sauté onions and garlic. 2. Add chopped vegetables (carrots, potatoes, peas) and vegetable broth. 3. Season with herbs and simmer until veggies are tender. Serve hot.'),
       ('Greek Salad', 4, (SELECT id FROM category WHERE name = 'Salad'),
        '1. Chop cucumbers, tomatoes, and bell peppers. 2. Mix with olives, feta cheese, and red onion. 3. Drizzle with olive oil and lemon juice. 4. Season with oregano before serving.'),
       ('Butternut Squash Risotto', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a pot, sauté onions and garlic in butter. 2. Add arborio rice and stir until coated. 3. Gradually add vegetable broth, stirring until absorbed. 4. Stir in roasted butternut squash and Parmesan cheese before serving.'),
       ('Eggplant Parmesan', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Preheat the oven to 375°F (190°C). 2. Slice eggplant, salt, and let sit to draw out moisture. 3. Bread and fry slices until golden. 4. Layer with marinara sauce and mozzarella in a baking dish and bake for 25-30 minutes. Serve hot.'),
       ('Avocado Toast', 6, (SELECT id FROM category WHERE name = 'Snack'),
        '1. Toast slices of bread. 2. Mash avocado and mix with lemon juice and salt. 3. Spread avocado on toast and top with radishes or poached eggs. Serve immediately.'),
       ('Rice Pudding', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. In a pot, combine rice, milk, sugar, and vanilla. 2. Cook over low heat, stirring until thickened. 3. Serve warm or chilled, topped with cinnamon.'),
       ('Spaghetti Aglio e Olio', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. Cook spaghetti according to package instructions. 2. In a pan, sauté minced garlic in olive oil. 3. Toss cooked spaghetti in garlic oil and add parsley. 4. Serve warm with grated Parmesan.'),
       ('Lentil Soup', 4, (SELECT id FROM category WHERE name = 'Soup'),
        '1. In a pot, sauté onions and carrots. 2. Add lentils, diced tomatoes, vegetable broth, and spices. 3. Simmer until lentils are tender. Serve hot.'),
       ('Mango Mousse', 12, (SELECT id FROM category WHERE name = 'Dessert'),
        '1. In a blender, puree ripe mangoes until smooth. 2. In a bowl, whip cream until soft peaks form. 3. Gently fold mango puree into whipped cream. 4. Chill before serving.'),
       ('Grilled Cheese Sandwich', 6, (SELECT id FROM category WHERE name = 'Snack'),
        '1. Heat a skillet over medium heat. 2. Butter bread slices and place cheese in between. 3. Grill until golden brown on both sides. Serve warm.'),
       ('Pineapple Fried Rice', 6, (SELECT id FROM category WHERE name = 'Main Course'),
        '1. In a wok, heat oil and add cooked rice. 2. Stir in diced pineapple, soy sauce, and vegetables. 3. Fry until heated through. 4. Serve warm, garnished with green onions.')
ON CONFLICT (name) DO NOTHING;